//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Item_ID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }

        public double price { get; set; }
        public Nullable<System.DateTime> Post_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Location { get; set; }
        public Nullable<int> catagoryid { get; set; }
    
        public virtual catagory catagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
